package com.jwtsampleapp.api.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.jwtsampleapp.api.model.AuthRequest;
import com.jwtsampleapp.api.model.AuthResponse;
import com.jwtsampleapp.api.model.User;
import com.jwtsampleapp.api.service.IUserService;
import com.jwtsampleapp.api.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {

	@Autowired
	private IUserService userService;
	
	@Autowired
	private JwtUtil jwtUtil;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@PostMapping("/save")
	public String saveUser(@RequestBody User user) {
		Integer id = userService.saveUser(user);
		String msg="User saved successfully with id :"+id;
		return msg;
	}
	
	
	@GetMapping("/sucess")
	public String successMsg() {
		return "You have logged in Successfully";
	}
	
	// validate user and generate token
	@PostMapping("/login")
	public AuthResponse loginUser(@RequestBody AuthRequest authRequest) {
		//validate username/pwd with dB
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						authRequest.getUserName(), authRequest.getPassword()));
		String token = jwtUtil.generateToken(authRequest.getUserName());
		return new AuthResponse(token, "Success Token Generated By Rakesh");	
	}
}
